# Dependencies
#markdown: kramdown
#highlighter:      pygments

# Permalinks
permalink:        /blog/:year/:month/:title.html
#relative_permalinks: true

# Setup
title:            Prahlad Yeri
tagline:          'Freelance Programmer and Writer'
description:      'Freelance Programmer and Writer'
url: https://prahladyeri.github.io
baseurl: ""

author:
  name:           'Prahlad Yeri'
  url:            https://prahladyeri.github.io

paginate:         10

# Custom vars
version:          2.1.1
theme_base: '0c'
# 08 == maroon
# 09 == light-brown
# 0a == cream
# 0b == green
# 0c == desktop-green
# 0e == magenta
# 0d == blue
# 0f == brown
# <any-other-value> == black (default)

adsense: "ca-pub-0428291735937735"
adsense_slot: "9729062115"
#disqus: 'prahladyeri-blog'

include:
    - _pages