# Dependencies
#markdown: kramdown
#highlighter:      pygments
highlighter: rouge

# Permalinks
permalink:        /blog/:year/:month/:title.html
#relative_permalinks: true
#permalink: /blog/:path/:year/:month/:title.html
# eg. /blog/es/:year/:month/:title.html


# Setup
title:            Prahlad Yeri
tagline:          'Freelance Programmer and Writer'
description:      'Freelance Programmer and Writer'
url: https://prahladyeri.github.io
baseurl: ""

author:
  name:           'Prahlad Yeri'
  url:            https://prahladyeri.github.io

paginate: 10
paginate_path: "/page/:num/"
tag_permalink: "/tag/:tag"

# Language specific
default_lang: en

# Custom vars
version: 2.1.42
adsense: "ca-pub-0428291735937735"
adsense_slot: "9729062115"
#disqus: 'prahladyeri-blog'
